### ISSUE TITLE
Some confusions

### ISSUE THREAD

**Issue by mehrdad-shokri** [SaltechSystems/couchbase_lite#38]
I'm so sorry for opening an issue here, I hope someone can enlighten me a bit.  
Currently, I'm developing a mobile app I've decided to use CouchDB as my backend. but for the mobile side apparently another CouchDB implementation must be available, I mean a NoSQL database running in user's mobile(Right?) So Couchbase lite does exactly that(Are there any opensource alternatives?)  
Also searching for flutter ports I found that there is [fluutercouch](https://github.com/fluttercouch/fluttercouch) can you explain in what way have you edited this library from that? any new features or refactors? (I saw that some API signatures are changed)
Can couchBase lite work with a CouchDB or should the backend be also Couchbase?  
Also, I'm concerned about switching from CouchDB to couchBase, does the community edition has all features of CouchDB and does its source code get updates from CouchDB?

**Comment by bawelter** [comment]
You should look at the couchbase forums / site for these answers.  But couchbase has more functionality than couchdb and was originally built on couchdb but is no longer backwards compatible because of some issues that couchdb could not support.  The biggest difference is the document conflict resolution strategy since couchbase is focused on a realtime offline first database solution.  Please don't respond to this and refer to the couchbase site / forums instead.  Thanks and have a great time developing!
