### ISSUE TITLE
Database.addDocumentChangeListener seems to be missing

### ISSUE THREAD

**Issue by matsunanaro** [SaltechSystems/couchbase_lite#42]
In Couchbase Lite SDK for iOS and Android, there is a method, Database.addDocumentChangeListener(withID:listener:),  that can be used to listen to change of a specific document. But this method seems to be missing in this SDK.

**Comment by matsunanaro** [comment]
I'm working on a fix for this one.

**Comment by bawelter** [comment]
I will be trying a squash and merge strategy on this next time to see if it will add you the the contributors page.  I didn't notice it wasn't doing this before but I wan't to make sure everyone is getting credit for the work they do.  Also make sure to change the version to v2.7.1+4 and add something to the change log so that we can create a release quickly.  I setup a CI/CD pipeline to make the releases faster.  You will know everything good is if it passes the CI tests when you do the pull request.  Let me know if you have any issues.

**Comment by matsunanaro** [comment]
I've now changed the version to v2.7.1+4 in CHANGELOG.md. But should I change the version in pubspec.yaml too ?

**Comment by bawelter** [comment]
> I've now changed the version to v2.7.1+4 in CHANGELOG.md. But should I change the version in pubspec.yaml too ?

Yes change that in the pubspec as well.
