### ISSUE TITLE
Supported authentication mechanisms

### ISSUE THREAD

**Issue by mehrdad-shokri** [SaltechSystems/couchbase_lite#45]
There are [several](https://docs.couchbase.com/sync-gateway/2.7/authentication.html) authentication methods supported by sync gateway. What mechanisms does this library support? I'm looking specifically for OpenID connect authentications

**Comment by bawelter** [comment]
Refer to https://docs.couchbase.com/sync-gateway/current/authentication.html on how to do this.  This library supports Auth through sessions as well as basic Auth as does the other couchbase lite libraries.

**Comment by mehrdad-shokri** [comment]
@bawelter does it support OpenID connect? Since it's available on [Sync gateway](https://docs.couchbase.com/sync-gateway/current/authentication.html#openid-connect)

**Comment by mehrdad-shokri** [comment]
Specifically, I'm looking for cookie authentication in remote replication. I handle session retrieval myself.

**Comment by SaltechDevelopers** [comment]
The app is responsible for retrieving the auth provider token and must send it to Sync Gateway which will return a session ID. The session ID can be used to configure the Couchbase Lite replicator or for other HTTP requests to the Sync Gateway REST API.


The session Authenticator supports setting a custom cookie name which the session is stored.  Otherwise I’m not sure what you mean by cookie authentication.  The session id is stored in a cookie though.

**Comment by mehrdad-shokri** [comment]
To clarify things, I wanna setup KeyCloack for OpenID connect provider, I'm not sure how to connect this lib to sync gateway through OpenID connect. The doc says that [it](https://docs.couchbase.com/sync-gateway/current/authentication.html#openid-connect) supports OpenID protocol. But I'm not sure whether I should retrieve session myself and attach to this lib as a cookie or can it be delegated to the lib completely.

**Comment by lchristille** [comment]
Sync Gateway and Couchbase Lite (and consequently this library) support implicit flow only. You'll have to interact with your Open ID provider in order to retrieve an access token, and configure Sync Gateway to be able to verify that token. You can refer to this article in the documentation https://docs.couchbase.com/sync-gateway/current/authentication.html#openid-connect

**Comment by function1983** [comment]
Couchbase documentation regarding this subject is honestly not really good. There are alot of gotchas until you figure out the pieces. I wish there is a step-by-step instruction on how to configure sync_gateway to accept google oauth2 and dynamically create an user. It took me the whole day but I am glad now that it works.

**Comment by bawelter** [comment]
Feel free to provide the documentation through a pull request / README documentation.

**Comment by bawelter** [comment]
This company is not affiliated with Couchbase.
